name: vi
description: A stock analysis application with web scraping capabilities.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  get_it: ^7.2.0
  injectable: ^2.1.0
  dartz: ^0.10.1
  html: ^0.15.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.0.1
  cloud_firestore: ^5.0.0
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.6.1
  url_launcher: ^6.1.9
  intl: ^0.17.0
  charts_flutter: ^0.12.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.3.2
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/translations/